Added '-' as an option char and implemented extensive tests
apache/commons-cli pull request #217
Opened 2024-01-08 12:44 UTC by Claudenw

Fix for CLI-322

Adds kabab-format options and extensive option name testing.

2024-01-08 13:15 UTC, garydgregory commented
@Claudenw 
I think you mean "kabab" -> "kebab". Always run `mvn` before you push with the latest from git master.

2024-01-11 10:10 UTC, Claudenw commented
> @Claudenw I think you mean "kabab" -> "kebab". Always run `mvn` before you push with the latest from git master.

Indeed, I do not know how to spell. :(

I did run 'mvn' before the push and everything worked.  Got "BUILD SUCCESS" result.  Just tried again and same thing.  I am addressing the issues from the build now.

2024-01-11 10:23 UTC, Claudenw commented
The build fails on 22-ea which fails with a spotbugs execution error,  It seems like spotbugs is not yet supported on 22-ea.

2024-01-11 19:20 UTC, garydgregory commented
RE 22-ea, that should be fixed by the next commons-parent release, so don't worry about that part.

2024-01-15 13:08 UTC, garydgregory commented on src/main/java/org/apache/commons/cli/OptionValidator.java
> +    private static boolean search(final char[] ary, final char c) {
'ary' is a poor parameter name here, almost any else else is better: 'chars', 'array, 'buffer'...

2024-01-15 13:15 UTC, garydgregory requested changes
Hi @Claudenw 
The site needs matching updates to document this feature.

2024-01-26 14:56 UTC, Claudenw commented
@garydgregory updated as requested

2024-02-04 12:51 UTC, garydgregory commented
Hi @Claudenw 
Run `mvn` locally before you push to catch these build failures.

2024-02-14 15:30 UTC, merged